[tool.isort]
multi_line_output = 3
include_trailing_comma = true
known_third_party = ["click", "pygments", "pytest", "setuptools", "simplejson"]
atomic = true

[tool.black]
include = '''(dsi|tests)'''

[tool.pylint."MESSAGES CONTROL"]
max-line-length = 120
disable = [
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    "too-few-public-methods"
]
